### PR TITLE
`ctapipe_io_nectarcam` fails when called with `ctapipe`

### PR DESCRIPTION
**Pull request by jlenain**
This PR should fix issue #41.

### CODE REVIEW

**Comment by jlenain** [comment]
@tibaldo , @vmarandon , I do not understand exactly why the [CI fails](https://github.com/cta-observatory/ctapipe_io_nectarcam/actions/runs/6580407494/job/17878319140?pr=42) at `src/ctapipe_io_nectarcam/tests/test_nectarcameventsource.py::test_loop_over_events`. Could you please briefly explain it to me ?
Thanks !

**Comment by vmarandon** [comment]
This is because the even file contain the even numbers. First event in this file is 2.

I would suggest to change the :

FIRST_EVENT_NUMBER_IN_FILE = 1
by : 
FIRST_EVENT_NUMBER_IN_FILE = 2

and : 
assert event.index.event_id == FIRST_EVENT_NUMBER_IN_FILE + I
by : 
assert event.index.event_id == FIRST_EVENT_NUMBER_IN_FILE + I*2

**Comment by jlenain** [comment]
Ah OK, thanks @vmarandon . And if we were to use an input file with odd events instead, would that break again the test?

**Comment by vmarandon** [comment]
Perhaps just put a comment in the test to explain what needs to be done if file change ?

**Review by vmarandon — APPROVED** [review]
The changes looks good to me

**Pull request merged**
