### PR TITLE
Ctapipe019

### PR DESCRIPTION
**Pull request by vmarandon**
Set of modifications to be used with ctapipe 0.18.

In summary : 

- Modification of the dependency file in order to use same package as ctapipe.
- Modification of the calibration file to comply with the format changes of ctapipe
- Few uniformisation of variable to be more similar with the LST equivalent. 
- Add function to get the total number of events (and define the __len__ function)
- Add the possibility to give the list of file to open in the constructor

 
(see the different commits for more details)

### CODE REVIEW

**Comment by vmarandon** [comment]
@tibaldo and @jlenain : I've removed the draft status. We can start to discuss the changes.

**Comment by jlenain** [comment]
Hi @vmarandon !
OK! First of all, if you agree, I woud like to publish a release before making the big jump!

**Comment by tibaldo** [comment]
Thank you for taking care of this. All changes look fine to me. One question: I am not sure if it is sufficient to pin the ctapipe version in setup.cfg or if it should also be specified in environment.yml?

**Comment by jlenain** [comment]
> Hi @vmarandon ! OK! First of all, if you agree, I woud like to publish a release before making the big jump!

We're already there: the last commit into `master` corresponds to the last tagged release `v0.1.2`.

**Comment by jlenain** [comment]
Last `ctapipe` release is `0.19.1`, published on May 11.

**Comment by vmarandon** [comment]
OK. I've fix the version to 0.19 in the environment.yml file
I suppose that the idea behind not put it was to always follow the latest version and fix if it breaks :-)

**Comment by jlenain** [comment]
Hum, the CI tests fail, trying to install astropy 4.3, instead of 5 on which ctapipe 0.19 relies. I think we should not be too permissive in setup.cfg and environment.yml.

**Comment by jlenain** [comment]
Quick tip: GitHub actions can be locally emulated using https://github.com/nektos/act, typicalky to test such behaviors.

**Pull request merged**
